/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as counterSol from './Counter.sol/index.js';
export type { counterSol };
import type * as donatchainSol from './Donatchain.sol/index.js';
export type { donatchainSol };
export * as factories from './factories/index.js';
export type { Counter } from './Counter.sol/Counter.js';
export { Counter__factory } from './factories/Counter.sol/Counter__factory.js';
export type { Donatchain } from './Donatchain.sol/Donatchain.js';
export { Donatchain__factory } from './factories/Donatchain.sol/Donatchain__factory.js';