/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Donatchain } from './Donatchain.js';
export * as factories from './factories/index.js';
export { Donatchain__factory } from './factories/Donatchain__factory.js';