version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  api:
    build: .
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    volumes:
      # נמפה את הקוד, אבל נחריג את node_modules כדי שיותקנו בתוך הקונטיינר (לינוקס)
      - ./:/app
      - /app/node_modules
    command: npm run dev

volumes:
  mongo-data:
